Resources:
  WebServers:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2c
      ImageId: ami-02bcbb802e03574ba
      InstanceType: t2.micro
      KeyName: particular
      SecurityGroups: 
          - "testeterraform"
      Tags:
          - Key: Name
            Value: WebServer
          - Key: User
            Value: matheus.costa    
      Volumes:
          - Device: /dev/xvdh 
            VolumeId: vol-062437f255ae6fc58

#https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
