Resources:
  MinhasBuckets:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: "financeiro-empresa-matheus"

#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-accesscontrol

